// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiwENyWXtwQjo9e5t2j3mRrkJylA7Wdc',
    appId: '1:308466822553:web:1a7f86200abecbcbdcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    authDomain: 'quantpulse-553db.firebaseapp.com',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
    measurementId: 'G-V2H0EJZKML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxasS4sOiyKfjJm5E5CKjcFDBzgbQlV0',
    appId: '1:308466822553:android:74ce407b1256b436dcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBilBedyn9ZvvHsenWiIC1KeUmaLvOHll4',
    appId: '1:308466822553:ios:024d2f0a0c6a3a58dcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
    androidClientId: '308466822553-tmuqodh8blqtcogm0lm2jk8vva4t1krb.apps.googleusercontent.com',
    iosClientId: '308466822553-pffua5favpbh1bc0ud9fi76t6g3bo5bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBilBedyn9ZvvHsenWiIC1KeUmaLvOHll4',
    appId: '1:308466822553:ios:024d2f0a0c6a3a58dcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
    androidClientId: '308466822553-tmuqodh8blqtcogm0lm2jk8vva4t1krb.apps.googleusercontent.com',
    iosClientId: '308466822553-pffua5favpbh1bc0ud9fi76t6g3bo5bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQiwENyWXtwQjo9e5t2j3mRrkJylA7Wdc',
    appId: '1:308466822553:web:2ef91e930265e832dcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    authDomain: 'quantpulse-553db.firebaseapp.com',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
    measurementId: 'G-B5SFPN96Z0',
  );
}
