// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiwENyWXtwQjo9e5t2j3mRrkJylA7Wdc',
    appId: '1:308466822553:web:1a7f86200abecbcbdcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    authDomain: 'quantpulse-553db.firebaseapp.com',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
    measurementId: 'G-V2H0EJZKML',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBilBedyn9ZvvHsenWiIC1KeUmaLvOHll4',
    appId: '1:308466822553:ios:024d2f0a0c6a3a58dcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQiwENyWXtwQjo9e5t2j3mRrkJylA7Wdc',
    appId: '1:308466822553:web:2ef91e930265e832dcf708',
    messagingSenderId: '308466822553',
    projectId: 'quantpulse-553db',
    authDomain: 'quantpulse-553db.firebaseapp.com',
    storageBucket: 'quantpulse-553db.firebasestorage.app',
    measurementId: 'G-B5SFPN96Z0',
  );

}